- pages/download.md
The current link takes you to https://ubuntu-mate.org/blog/ubuntu-mate-zesty-final/ which 404's. I changed the link to the release post I found: https://ubuntu-mate.org/blog/ubuntu-mate-zesty-final-release/ 
This is a PR for Issue #2
> Link to Release Announcement for 17.04 goes to 404 page

- blog/20170831-ubuntu-mate-artful-beta1.md
There's a typo in the workaround, and there's also a better one available.
> Fix cryptswap workaround

- pages/index.md
Fixed a grammar error where the information about the RPi and GPD Pocket was given.
> Fix typo in main page

- pages/team.md
For Ikey Doherty and Sefan Ric, the link to the Solus home page is broken.  It has changed from solusproject.com to getsol.us
I have updated the team.md page to reflect this change.
> Fix broken Solus link

- blog/20191018-ubuntu-mate-eoan-beta.md
- pages/download.md
Fix typos in `/blog/20191018-ubuntu-mate-eoan-beta.md` and `/pages/download.md`.
> Typo-Branch

- pages/how-to-verify-downloads.md
The old instructions were slightly confusing IMHO because one step was for base ubuntu (not MATE) and the other for the EOL'ed 15.10. This now shows the ubuntu-mate iso for both steps and updates the version to 18,04.
My editor also automatically removed a trailing whitespace from line 31... if this should have stayed for some reason I'll be happy to fix this. :smile: 
Cheers!
Fred
> Update version for GPG verification steps

- blog/20140925-ubuntu-mate-beta2.md
- pages/roadmap.md
It redirects to a click tracker parked domain.
> Remove obsolete link to Sonar GNU/Linux

- pages/logo-guidelines.md
In several places in the logo guidelines, there was incorrect grammar.  There were also several places where the wording choice was poor.  I have attempted to correct these errors.
> Fix typos and unclear wording

- pages/how-to-verify-downloads.md
- pages/raspberry-pi.md
- pages/roadmap.md
When going through the documentation I noticed this, I believe the word should be authentic and not authenticate. Only my second PR in a few years so I hope I've done it correctly.
> Fixed documentation typo

- pages/umpc.md
Under the "What works" heading, there was a typo where "wheel" (in 'Enable scroll wheel emulation for Xorg') was misspelled as "whell."  This file change fixes that typo.
> Fix "wheel" typo

- _sass/lib/slick.scss
Update fixes the Slick buttons on narrow devices with viewable screen sizes of 475px or less:
Testing with other devices shows a consistent appearance:
> CSS: fix Slick button alignment on mobile devices

- _sass/_partials/_banner.scss
Seems Safari doesn't like it when other OSes look good. This is how Safari shows the banner on MacOS 10.15.x:
This is how Safari shows the banner on an iPad running iPad OS 13.5:
Neither of these are great. However, it can be resolved by using a *Safari-specific* value in the image CSS: `height: intrinsic`.
This will ensure the aspect ratio is maintained just like it is in Chrome:
and Opera:
and even Edge:
Because `height: intrinsic` is not understood by any browser aside from Safari, and because there is no *good* way to write Safari-only CSS, the ugly kludge in this pull request was created. Testing shows that every non-Apple browser ignores the `intrinsic` and reads the existing `auto` value defined on line 26 of `_banner.scss`.
> CSS: fix for banner image skewing in Safari

- pages/get-involved-bug-fixing.md
- pages/get-involved-bug-triage.md
- pages/support.md
Clarified bug-triage and bug-fixing, added more explicit links to Ubuntu MATE Launchpad page, emphasized community resources for Support page.
> Updated Bug/Support Pages Take 2

- _data/known_issues.yml
Clock not appearing on panel upon upgrade to 20.10
> Update known issues for Clock missing in panel

- README.md
On ubuntu 20.10, I needed to add the `translate-toolkit` package to be able to build the website.
> Missing translate-toolkit package to build the website

- .github/workflows/main.yml
- Gemfile.lock
It seems some RSS clients use `<updated>` instead of `<published>` in `/feed.xml` to determine if there's changes to posts. Up to now, the "updated" date was being reset to the time of deployment.
This corrects the dates by using the git timestamp for the file. This does **not** fix RSS localized versions of the site, as those files are generated at build time. Some additional work would be needed to fix it there.
Also some general maintenance -- I ran `bundle update` to bump to the latest versions.
> Fix RSS modification dates

- _data/downloads.yml
- _data/feature-grid.yml
- _data/known_issues.yml
- _layouts/feature-grid.html
- _posts/2021-04-22-ubuntu-mate-hirsute.md
Resolve 404 error on Downloads page for Release Notes. Update feature-grid for 21.04
> Fix downloads.yml for hirsute

- _layouts/download.html
- _sass/_layouts/_downloads.scss
Now that i386 is gone, it would be nice to use less whitespace and bring the device ports and links closer to the top.
> Condense download index page

- _data/downloads.yml
Drop 20.10 for amd64 as now EOL
> Drop 20.10 for amd64 as now EOL

- pages/raspberry-pi-compatibility.md
Fix a typo in [raspberry-pi-compatibility.md](https://github.com/ubuntu-mate/ubuntu-mate.org/blob/master/pages/raspberry-pi-compatibility.md)
> Fix a typo in raspberry-pi-compatibility.md

- _posts/2022-03-29-ubuntu-mate-jammy.md
I noticed a typo in the release notes for Ubuntu MATE 22.04. The word "get" is repeated twice. This PR removes the duplication.
> Remove duplicated word (typo – "get get")

- _data/downloads.yml
The main cdimage iso image has been renamed with the point release and this repoints the download links
Tested OK locally so hopefully good to go
> update iso download data for 22.04.1 release

- _posts/2022-03-29-ubuntu-mate-jammy.md
Fix typo (corrected "Boutqiue" to "Boutique") 
in the Ubuntu MATE 22.04 LTS Release Notes.
> Fix typo ("Boutqiue") in the Ubuntu Jammy Release Notes

- _data/known_issues.yml
The "Brazilian Portuguese" locale is "pt_BR" and not "pt_BL"  (there is no locale that is called "pt_BL").
Fixing the known issues reference for Ubuntu MATE 20.04 accordingly.
> Change "pt_BL" to "pt_BR" in "Known Issues"

- _posts/2022-09-29-ubuntu-mate-kinetic.md
Changed word "compliment" to "complement" in the following sentence of  the "Ubuntu MATE 22.10" Release Notes:
"A new utility, User Manager, has been added to complement the suite of MATE tools."
> Change word "compliment" to "complement"

- _data/downloads.yml
Update downloads.yml to correct ISO size for Ubuntu MATE 20.04.5 (Focal Fossa)
The file "ubuntu-mate-20.04.5-desktop-amd64.iso" is 4.1 GB in size and not 3.2 GB
> Update downloads.yml to correct ISO size for focal

- _data/downloads.yml
I went to download Ubuntu MATE 22.04 for AMD64 and noticed that the download links are dead. By going to [the Ubuntu releases download page](https://cdimage.ubuntu.com/ubuntu-mate/releases/22.04/release/), it looks like everything was updated to 22.04.2 yesterday, and the old resources are gone. I believe that this PR will bump everything accordingly from 22.04.1 to 22.04.2.
> Update AMD64 downloads data to 22.04.2

- _posts/2023-04-20-ubuntu-mate-lunar-lobster.md
Replaced the following Update Manager mention in 
the Ubuntu MATE 23.04 Release Notes:
"New distribution release '22.10' is available"
by the following one:
"New distribution release '23.04' is available"
> Replaced Update Manager reference from 22.10 to 23.04

- _posts/2014-07-14-how-to-say-mate.md
The YouTube video URL to the video by Michael Tunnell that 
explains how to pronounce MATE stopped working (it is 
showing the "This video is unavailable" error message).
So I am replacing that URL by another YouTube URL also by 
Michael Tunnell (maybe it is the same video as the original but 
in another location).
Besides that, due to the end of Google Plus, the link to Michael Tunnell's 
posts in Google Plus also stopped working. So, I am replacing that URL 
by a link to his YouTube channel.
> blog : replace video URL about MATE pronunciation

- _data/downloads.yml
As @guiverc (Chris Guiver) has mentioned in:
https://ubuntu-mate.community/t/site-links-need-updating/27181
... "Ubuntu 22.04.4 (and flavors) were released":
https://fridge.ubuntu.com/2024/02/22/ubuntu-22-04-4-lts-released/
But the download links at:
https://ubuntu-mate.org/download/amd64/jammy/ 
... are still pointing to :
https://cdimage.ubuntu.com/ubuntu-mate/releases/22.04/release/ubuntu-mate-22.04.3-desktop-amd64.iso
.... which no longer exists (returns a 404 error). 
This commit and Pull Request replaces "22.04.3" by "22.04.4"  in the version number, and updates the SHA256 checksum and Magnet link accordingly.
> feat: update downloads for 22.04 from 22.04.3 to 22.04.4

- _data/downloads.yml
Ubuntu 23.04 ("Lunar Lobster") reached EOL (End Of Life)  as of 25th January 2024. So, this Commit and "Pull Request"  serves to remove the download links for "23.04" from  https://ubuntu-mate.org/download/amd64/
REFERENCES:
1 - @guiverc (Chris Guiver) post in: 
https://fridge.ubuntu.com/2024/01/26/ubuntu-23-04-lunar-lobster-reached-end-of-life-on-january-25-2024/
2 - ... which, as that post mentions, is a repost of a "ubuntu-announce" mailing list post by Brian Murray available in:  https://lists.ubuntu.com/archives/ubuntu-announce/2024-January/000298.html
> Removing 23.04 from downloads as it went EOL

- _data/downloads.yml
As tkn (thom) has correctly mentioned, in an Ubuntu MATE  Community post, the downloads page has a small typo, by referring to Noble Numbat as being 22.04 when it should be 24.04. This commit and pull request fixes that. 
REFERENCES:
https://ubuntu-mate.community/t/small-typo-on-download-page-numbat-22-04-instead-of-24-04/27280
> fix: Update downloads.yml to correct version of Noble Numbat

- _data/downloads.yml
As @guiverc (Chris Guiver) has mentioned in:
https://ubuntu-mate.community/t/ubuntu-mate-24-04-1-lts-released/28138
... "Ubuntu MATE 24.04.1 LTS released":
https://ubuntu-news.org/2024/08/30/ubuntu-24-04-1-lts-released/
However, the download links at:
https://ubuntu-mate.org/download/amd64/jammy/
... are still pointing to :
https://cdimage.ubuntu.com/ubuntu-mate/releases/noble/release/ubuntu-mate-24.04-desktop-amd64.iso
.... which no longer exists (returns a 404 error).
This commit and Pull Request replaces "24.04" by "24.04.1" in the version number, and updates the SHA256 checksum and Magnet link accordingly.
> feat: update downloads for 24.04 from 24.04 to 24.04.1

- _data/downloads.yml
According to:
https://lists.ubuntu.com/archives/ubuntu-announce/2025-February/000308.html
... Ubuntu 24.04.2 LTS (2nd point release of "Noble Numbat") was released today (20th February 2025)  for Ubuntu and its several flavors / flavours (including "Ubuntu MATE").
The download links at:
https://ubuntu-mate.org/download/amd64/noble/
... are currently still pointing to :
https://cdimage.ubuntu.com/ubuntu-mate/releases/noble/release/ubuntu-mate-24.04.1-desktop-amd64.iso
This commit and Pull Request replaces "24.04.1" by "24.04.2" in the version number and updates the location (URL) and SHA256 checksum of the ISO file and updates the Magnet link accordingly.
> feat: update downloads for 24.04 from 24.04.1 to 24.04.2

- _data/downloads.yml
Ubuntu MATE 22.04 reaches end of life this month (April 2025) as an Ubuntu flavour. Not sure on the exact date, so perhaps one to be merged at the end of the month, or when 25.04 is released.
Removing 22.04 also means the end of Raspberry Pi downloads. It's unlikely we'll see any newer images (see 88c6cff290430570b3dd4f766ed8b84a7d90a53b) but the [Raspberry Pi download FAQ page](https://ubuntu-mate.org/raspberry-pi/download/) is up-to-date with the details, which is linked from the _new_ download page to inform users what to do next.
_As an aside, the website got a Yaru-MATE update, and the downloads page is now simplified._
> Remove 22.04 LTS as EOL

- _posts/2025-04-15-ubuntu-mate-plucky-puffin.md
As Chris Guiver (@guiverc) has pointed out in 
https://ubuntu-mate.community/t/typo-in-ubuntu-mate-25-04-release-notes/29294
... the version of the Linux Kernel in Ubuntu MATE 25.04 ("Plucky Puffin") is 6.14 and not 6.15
This commit and pull request makes that correction.
> Update 2025-04-15-ubuntu-mate-plucky-puffin.md: Kernel is 6.14
