conf.py
same as done with utopic, wily, xenial
=> redirect trusty and vivid links to download page

blog/20170727-ubuntu-mate-artful-alpha2.md, blog/20170831-ubuntu-mate-artful-beta1.md, blog/20170928-ubuntu-mate-artful-beta2.md, blog/20171019-ubuntu-mate-artful-final-release.md
Since some blog posts can be rendered in the same page, the elements should use unique ids.
=> Correct slider divs to use different ids

pages/raspberry-pi.md
- Fixes a typo in the word `disable`
- fixes some grammar.
=> Fix typo & grammar in raspberry-pi.md

blog/20180426-ubuntu-mate-bionic-final-release.md
I haven't added or changed any content, just proof-read it.
Suggestions for actual stuff to add:
* Explain that Alt invokes the HUD
* What actually _is_ HiDPI? Will it be automatically turned on? Why or why not might that be a good idea? If not, how do I turn it on? If I don't like it how do I turn it off? Does it work with Compiz or just Marco? If I'm already running Ubuntu MATE and I upgrade, and I've tried turning on HiDPI myself already, is this likely to break, or will it seamlessly do it the right way this time?
* Show off the new mate-dock-applet quickmenus and window selector, since the new stuff is pretty and the existing 16.04 stuff really, really isn't
* For the love of God, Montresor, explain how the new emoji input thing works! How do I invoke it? Does it work in every …
=> Proof-reading

files/assets/downloads.json
No longer the latest and greatest.
=> Deprecate Artful on the download page.

pages/faq.md
Hi, 
I noticed 2 typos and fixed them in this PR.
=> Fix 2 typos in FAQ

pages/logo-guidelines.md
There are a few places on the logo guidelines page that either have awkward wording or incorrect grammar.  I have endeavored to fix at least some of those.
=> Edits for clarity and grammar

pages/what-is-ubuntu-mate.md
Changed the wording to 'Wikipedia defines a desktop environment as:'
=> Change wording for DE definition

pages/team.md
Updated Adam Smith, Jack Mohegan, Jonathan Nadeau, and Ivan Pejić
=> Updated Team Member links

pages/faq.md
Markdownified and lightly edited version of the FAQ
=> FAQ.md update

pages/get-involved-crowdfund.md, pages/testimonials.md
Testimonials with names/urls/quotes and new text for Crowdfunding page. (I don't have pound signs on my keyboard, so Luke, if you could add them to the currency amounts towards the bottom, it would be much appreciated! Also, I put in emojis in Markdown, but if they don't work feel free to delete them. They're just in one line. Here's hoping this pull request is smoother than the last!
=> New text for testimonials and get-involved-crowdfund pages

pages/get-involved-artwork.md, pages/get-involved-community-support.md, pages/get-involved-spread-word.md
Added new content for community-support, artwork, and spread-word
=> get-involved sections

_data/team.yml, pages/team.md
Updated team.md and /_data/team.yml
=> Team page and yml file

pages/testimonials.md
Updated testimonials to showcase/highlight 20.04 LTS reviews
=> Testimonials

.bundle/config, _data/navigation.yml, _data/strings.yml, _layouts/post-download.html, _sass/_base.scss, _sass/_layouts/_catalogue.scss, pages/support.md
The new support page is built, incorporating the new known_issues  YAML and the partial that incorporates it into a table. Page has been tested via local build and ./scripts/test.sh
=> New Support page with navigation changes

_data/downloads.yml
Verified and updated checksums.
=> Download checksum verifications

_data/team.yml
=> Team: Add bigpod and Sai

_data/team.yml
Edited Monica's data to note her recent Ubuntu membership.
=> EDIT: Monica Madon

pages/shop-apparel.md
Reordered listings to place Spreadshirt entries listed first
=> UPDATE: shop-apparel.md

_drafts/2021-XX-XX-hirsute-beta.md
Used template to create a placeholder draft for the hirsute beta, which can be revised/updated as needed
=> ADDED: hirsute beta release placeholder to /_drafts/

_data/team.yml, pages/team.md
Added M.aD to team page, added Luke H and Jon U back to active team and removed from previous sections.
=> UPDATE: team.md and /_data/team.yml

_posts/2021-XX-XX-hirsute-final.md
Please make changes to this doc, which will become the final release notes.
=> ADD: Hirsute Final DRAFT

_drafts/2021-04-22-ubuntu-mate-hirsute.md
Minor corrections to versions, typo etc.
=> Minor changes and typo correction

_data/downloads.yml, _data/known_issues.yml, pages/download.md, pages/requirements.md
=> Remove 18.04 LTS EOL

pages/irc.md
=> Update irc to Libera.Chat

_sass/_buttons.scss
Will make active buttons more discoverable for users navigating the site with a mouse.
=> Improve button accessibility for mouses.

_data/team.yml
Update links for Jon Uhler. Also bump site for 2022.
=> Update Team Page links

_data/downloads.yml, _layouts/feature-grid.html
Remove 21.04 Downloads and Feature Grid
=> Remove EOL 21.04

_data/downloads.yml
=> Update for 20.04.4

_includes/embed/highlight-video.html, pages/about.md
=> Update Highlights Video

pages/testimonials.md
=> Add 22.04 Testimonial

pages/testimonials.md
Replace 20.04 showcase with 22.04
=> Replace 20.04 showcase with 22.04

_data/feature-grid.yml, _layouts/feature-grid.html
Add 22.04, drop reference to 21.04
=> Add 22.04 to Feature grid

_drafts/2022-09-29-ubuntu-mate-kinetic.md
"supports for MATE Xfce" -> "supports MATE Xfce"
=> [docs] typo correction

_data/downloads.yml
Update Focal download to 20.04.6
=> Update Focal download to 20.04.6

_data/feature-grid.yml, _layouts/feature-grid.html
Add 23.04 to and remove 20.04 from feature grid.
=> Update feature grid 

_data/downloads.yml, _data/feature-grid.yml, _layouts/feature-grid.html
Remove EOL 20.04 from main downloads section
=> Remove EOL 20.04 from downloads

_data/downloads.yml, _data/team.yml
Remove 22.10 EOL and team page update
=> Remove 22.10 EOL 

_data/downloads.yml
=> Update download to 22.04.3

_data/apps.yml
updating Seahorse src_url with current upstream Git URL
=> Gnome has moved to Gitlab some time ago - few apps src url needs correction
